package com.sarafrika.apps.mpesaservice.dtos;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Response from Dynamic QR Code generation
 * Returned when generating a QR code for M-Pesa payments
 */
@Schema(description = "Dynamic QR Code generation response from Daraja API")
public record QRCodeResponse(

        @Schema(description = "Response code from Safaricom (00 = success)", example = "00")
        @JsonProperty("ResponseCode")
        String responseCode,

        @Schema(description = "Request ID generated by Safaricom", example = "QRCode_2023_07_27_10_42_47_123456")
        @JsonProperty("RequestID")
        String requestId,

        @Schema(description = "Response description", example = "The service request has been accepted successfully.")
        @JsonProperty("ResponseDescription")
        String responseDescription,

        @Schema(description = "Base64 encoded QR code image",
                example = "iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz...")
        @JsonProperty("QRCode")
        String qrCode
) {

    /**
     * Check if QR code generation was successful
     */
    public boolean isSuccessful() {
        return "00".equals(responseCode);
    }

    /**
     * Get QR code as data URL for direct use in HTML/web
     */
    public String getQRCodeDataUrl() {
        if (qrCode != null && !qrCode.isEmpty()) {
            return "data:image/png;base64," + qrCode;
        }
        return null;
    }

    /**
     * Check if QR code data is available
     */
    public boolean hasQRCode() {
        return qrCode != null && !qrCode.trim().isEmpty();
    }
}