package com.sarafrika.apps.mpesaservice.dtos;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Response from STK Push initiation request
 * Returned when initiating a Lipa na M-Pesa Online payment
 */
@Schema(description = "STK Push initiation response from Daraja API")
public record StkPushResponse(

        @Schema(description = "Merchant request ID generated by Safaricom", example = "21605-295434-4")
        @JsonProperty("MerchantRequestID")
        String merchantRequestId,

        @Schema(description = "Checkout request ID used for status queries", example = "ws_CO_04112017184930742")
        @JsonProperty("CheckoutRequestID")
        String checkoutRequestId,

        @Schema(description = "Response code from Safaricom (0 = success)", example = "0")
        @JsonProperty("ResponseCode")
        String responseCode,

        @Schema(description = "Response description from Safaricom", example = "Success. Request accepted for processing")
        @JsonProperty("ResponseDescription")
        String responseDescription,

        @Schema(description = "Customer message displayed on phone", example = "Check your phone for the M-PESA pin prompt")
        @JsonProperty("CustomerMessage")
        String customerMessage
) {}

